/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import "RCTRootView.h"

#import "Local.h"
#import "Intercom/intercom.h" 
#import "RCTPushNotificationManager.h"
@import Tune;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // Initialize Intercom
#ifdef DEBUG
  [Intercom setApiKey:@"ios_sdk-5ac42327f3204035d768d240440eaa35bca8c2cb" forAppId:@"rt4wkcg2"];
#else
  [Intercom setApiKey:@"ios_sdk-df60bc96266dbeaa066450ea8fe26898924b44f5" forAppId:@"a0z9ng0t"];
#endif
  // This registers an unidentifed user with Intercom.
  [Intercom registerUnidentifiedUser];
    
  // Initialize TUNE
  [Tune initializeWithTuneAdvertiserId:@"190547"
                     tuneConversionKey:@"9a652aa94e0e84487aae98fbe8f888ec"];
  
  NSURL *jsCodeLocation;
#if defined(kRCTDevServerHost) && defined(DEBUG)
  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */

  jsCodeLocation = [NSURL URLWithString:[NSString stringWithFormat:@"http://%@:8081/index.ios.bundle?platform=ios&dev=true", kRCTDevServerHost]];
#else
  /**
   * OPTION 2
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by "Bundle React Native code and images" build step.
   */
  
   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"TredMobile"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];

  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  rootView.backgroundColor = [UIColor colorWithRed:2.0f/255.0f
                  green:186.0f/255.0f
                   blue:242.0f/255.0f
                  alpha:1.0f];
  
  
  return YES;
}

- (void)applicationDidBecomeActive:(UIApplication *)application
{
  #ifndef DEBUG
    // Attribution will not function without the measureSession call included
    [Tune measureSession];
  #endif
}

// Required to register for notifications
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
  [RCTPushNotificationManager didRegisterUserNotificationSettings:notificationSettings];
}
// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [RCTPushNotificationManager didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
// Required for the notification event.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification
{
  [RCTPushNotificationManager didReceiveRemoteNotification:notification];
}

@end
